### ISSUE TITLE
Sorting cards (Not really an issue)

### ISSUE THREAD

**Issue by Jurgenn22** [bessarabov/home-assistant-cards#3]
Nice website! Thanks for that. 

It would be nice if you could sort the cards by #new added # at the top. Don't know if that's possible, I'm not a developer.
Or can I see the latest cards somewhere?

regards

**Comment by KTibow** [comment]
How would this be sorted? Last update to it? First time added? How old the repo is?

**Comment by Jurgenn22** [comment]
@KTibow 
I would say, if possible, the option to sort the cards by completely new card added. First time added indeed.
It concerns the website https://home-assistant-cards.bessarabov.com, to add the sorting option.

**Comment by bessarabov** [comment]
Thank you! I really like this idea! 

I've added 2 more columns:

 * created — Date and time when the repository was created
 * last commit — Date and time of the last commit in default branch

And it is possible to resort data by that columns.

![Screen Shot 2020-11-19 at 16 21 22](https://user-images.githubusercontent.com/47263/99671943-cf2f5480-2a83-11eb-949a-6b1241eaf09d.png)

**Comment by Jurgenn22** [comment]
@bessarabov 
Thank you for the quick response. And for the update on the site.
