### ISSUE TITLE
auto-reload-card

### ISSUE THREAD

**Issue by jhein05** [bessarabov/home-assistant-cards#4]
https://github.com/ben8p/lovelace-auto-reload-card

**Comment by KTibow** [comment]
Is it really *a card*?
Could you show a screenshot?

**Comment by bessarabov** [comment]
> https://github.com/ben8p/lovelace-auto-reload-card

I've added this card — https://home-assistant-cards.bessarabov.com/card/48f12a9af1ac

**Comment by bessarabov** [comment]
> Is it really _a card_?
> Could you show a screenshot?

You are asking a great question. I was thinking a lot what is **a card** for this project. I have decided that **a card** is everything that is put into `www/` directory and can be used in UI YAML with `type: 'custom:NNN'`. `badge-card` is not visible, but It satisfies the requirements that I came to.
