### ISSUE TITLE
Image for slider-button-card

### ISSUE THREAD

**Issue by mattieha** [bessarabov/home-assistant-cards#7]
![slider-button-card](https://user-images.githubusercontent.com/3931195/122134337-ab2bca00-ce3e-11eb-8bda-4cc03184447a.png)

**Comment by bessarabov** [comment]
Added. Thank you!

https://home-assistant-cards.bessarabov.com/card/slider-button-card

**Comment by mattieha** [comment]
Thank you for this awesome collection/repo!
